/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ExemplosRouteImport } from './routes/exemplos'
import { Route as FuncionalidadesRouteImport } from './routes/funcionalidades'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PlanosBasicoRouteImport } from './routes/planos.basico'
import { Route as PlanosProfissionalRouteImport } from './routes/planos.profissional'
import { Route as PlanosEnterpriseRouteImport } from './routes/planos.enterprise'
import { Route as PlanosMensalRouteImport } from './routes/planos.mensal'
import { Route as EventoRouteImport } from './routes/evento'
import { Route as EventosPresenciaisRouteImport } from './routes/eventos.presenciais'
import { Route as EventosVirtuaisRouteImport } from './routes/eventos.virtuais'
import { Route as EventosHibridosRouteImport } from './routes/eventos.hibridos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as EmpresaDashboardRouteImport } from './routes/empresa.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosRoute = ExemplosRouteImport.update({
  id: '/exemplos',
  path: '/exemplos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionalidadesRoute = FuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosBasicoRoute = PlanosBasicoRouteImport.update({
  id: '/planos/basico',
  path: '/planos/basico',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosProfissionalRoute = PlanosProfissionalRouteImport.update({
  id: '/planos/profissional',
  path: '/planos/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosEnterpriseRoute = PlanosEnterpriseRouteImport.update({
  id: '/planos/enterprise',
  path: '/planos/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosMensalRoute = PlanosMensalRouteImport.update({
  id: '/planos/mensal',
  path: '/planos/mensal',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoRoute = EventoRouteImport.update({
  id: '/evento',
  path: '/evento',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosPresenciaisRoute = EventosPresenciaisRouteImport.update({
  id: '/eventos/presenciais',
  path: '/eventos/presenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosVirtuaisRoute = EventosVirtuaisRouteImport.update({
  id: '/eventos/virtuais',
  path: '/eventos/virtuais',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosHibridosRoute = EventosHibridosRouteImport.update({
  id: '/eventos/hibridos',
  path: '/eventos/hibridos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaDashboardRoute = EmpresaDashboardRouteImport.update({
  id: '/empresa/dashboard',
  path: '/empresa/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/exemplos': typeof ExemplosRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/planos/basico': typeof PlanosBasicoRoute
  '/planos/profissional': typeof PlanosProfissionalRoute
  '/planos/enterprise': typeof PlanosEnterpriseRoute
  '/planos/mensal': typeof PlanosMensalRoute
  '/evento': typeof EventoRoute
  '/eventos/presenciais': typeof EventosPresenciaisRoute
  '/eventos/virtuais': typeof EventosVirtuaisRoute
  '/eventos/hibridos': typeof EventosHibridosRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/exemplos': typeof ExemplosRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/planos/basico': typeof PlanosBasicoRoute
  '/planos/profissional': typeof PlanosProfissionalRoute
  '/planos/enterprise': typeof PlanosEnterpriseRoute
  '/planos/mensal': typeof PlanosMensalRoute
  '/evento': typeof EventoRoute
  '/eventos/presenciais': typeof EventosPresenciaisRoute
  '/eventos/virtuais': typeof EventosVirtuaisRoute
  '/eventos/hibridos': typeof EventosHibridosRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/exemplos': typeof ExemplosRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/planos': typeof PlanosRoute
  '/planos/basico': typeof PlanosBasicoRoute
  '/planos/profissional': typeof PlanosProfissionalRoute
  '/planos/enterprise': typeof PlanosEnterpriseRoute
  '/planos/mensal': typeof PlanosMensalRoute
  '/evento': typeof EventoRoute
  '/eventos/presenciais': typeof EventosPresenciaisRoute
  '/eventos/virtuais': typeof EventosVirtuaisRoute
  '/eventos/hibridos': typeof EventosHibridosRoute
  '/sobre': typeof SobreRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/empresa/dashboard': typeof EmpresaDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contactos'
    | '/exemplos'
    | '/funcionalidades'
    | '/planos'
    | '/planos/basico'
    | '/planos/profissional'
    | '/planos/enterprise'
    | '/planos/mensal'
    | '/evento'
    | '/eventos/presenciais'
    | '/eventos/virtuais'
    | '/eventos/hibridos'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/empresa/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contactos'
    | '/exemplos'
    | '/funcionalidades'
    | '/planos'
    | '/planos/basico'
    | '/planos/profissional'
    | '/planos/enterprise'
    | '/planos/mensal'
    | '/evento'
    | '/eventos/presenciais'
    | '/eventos/virtuais'
    | '/eventos/hibridos'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/empresa/dashboard'
  id:
    | '__root__'
    | '/'
    | '/contactos'
    | '/exemplos'
    | '/funcionalidades'
    | '/planos'
    | '/planos/basico'
    | '/planos/profissional'
    | '/planos/enterprise'
    | '/planos/mensal'
    | '/evento'
    | '/eventos/presenciais'
    | '/eventos/virtuais'
    | '/eventos/hibridos'
    | '/sobre'
    | '/admin/dashboard'
    | '/admin/login'
    | '/empresa/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactosRoute: typeof ContactosRoute
  ExemplosRoute: typeof ExemplosRoute
  FuncionalidadesRoute: typeof FuncionalidadesRoute
  PlanosRoute: typeof PlanosRoute
  PlanosBasicoRoute: typeof PlanosBasicoRoute
  PlanosProfissionalRoute: typeof PlanosProfissionalRoute
  PlanosEnterpriseRoute: typeof PlanosEnterpriseRoute
  PlanosMensalRoute: typeof PlanosMensalRoute
  EventoRoute: typeof EventoRoute
  EventosPresenciaisRoute: typeof EventosPresenciaisRoute
  EventosVirtuaisRoute: typeof EventosVirtuaisRoute
  EventosHibridosRoute: typeof EventosHibridosRoute
  SobreRoute: typeof SobreRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EmpresaDashboardRoute: typeof EmpresaDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos': {
      id: '/exemplos'
      path: '/exemplos'
      fullPath: '/exemplos'
      preLoaderRoute: typeof ExemplosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades': {
      id: '/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof FuncionalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/basico': {
      id: '/planos/basico'
      path: '/planos/basico'
      fullPath: '/planos/basico'
      preLoaderRoute: typeof PlanosBasicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/profissional': {
      id: '/planos/profissional'
      path: '/planos/profissional'
      fullPath: '/planos/profissional'
      preLoaderRoute: typeof PlanosProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/enterprise': {
      id: '/planos/enterprise'
      path: '/planos/enterprise'
      fullPath: '/planos/enterprise'
      preLoaderRoute: typeof PlanosEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/mensal': {
      id: '/planos/mensal'
      path: '/planos/mensal'
      fullPath: '/planos/mensal'
      preLoaderRoute: typeof PlanosMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento': {
      id: '/evento'
      path: '/evento'
      fullPath: '/evento'
      preLoaderRoute: typeof EventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/presenciais': {
      id: '/eventos/presenciais'
      path: '/eventos/presenciais'
      fullPath: '/eventos/presenciais'
      preLoaderRoute: typeof EventosPresenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/virtuais': {
      id: '/eventos/virtuais'
      path: '/eventos/virtuais'
      fullPath: '/eventos/virtuais'
      preLoaderRoute: typeof EventosVirtuaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/hibridos': {
      id: '/eventos/hibridos'
      path: '/eventos/hibridos'
      fullPath: '/eventos/hibridos'
      preLoaderRoute: typeof EventosHibridosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/dashboard': {
      id: '/empresa/dashboard'
      path: '/empresa/dashboard'
      fullPath: '/empresa/dashboard'
      preLoaderRoute: typeof EmpresaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactosRoute: ContactosRoute,
  ExemplosRoute: ExemplosRoute,
  FuncionalidadesRoute: FuncionalidadesRoute,
  PlanosRoute: PlanosRoute,
  PlanosBasicoRoute: PlanosBasicoRoute,
  PlanosProfissionalRoute: PlanosProfissionalRoute,
  PlanosEnterpriseRoute: PlanosEnterpriseRoute,
  PlanosMensalRoute: PlanosMensalRoute,
  EventoRoute: EventoRoute,
  EventosPresenciaisRoute: EventosPresenciaisRoute,
  EventosVirtuaisRoute: EventosVirtuaisRoute,
  EventosHibridosRoute: EventosHibridosRoute,
  SobreRoute: SobreRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  EmpresaDashboardRoute: EmpresaDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { router } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
